### ISSUE TITLE
more robust service start

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/private-data-objects#182] opened 2019-04-22 19:04 UTC
- move pgrep from various test scripts into *-start.sh (including adding it also to ss-start.sh where previously we did not have)
- add a test in es-start.sh when (maybe optionally/based on option) returns only once all services are up and running ...

**Comment by cmickeyb** [comment] 2019-04-29 18:40
duplicate of #164

**Closed by cmickeyb** 2019-04-29 18:40 UTC
Labels: duplicate, enhancement
