### ISSUE TITLE
PDO/CCF: Add HW mode support

### ISSUE THREAD

**Issue by prakashngit** [hyperledger-labs/private-data-objects#262] opened 2020-04-07 14:26 UTC
Currently, PDO/CCF integration works only in SGX_MODE=SIM for PDO & cmake flag TARGET=virtual for ccf. To support end-to-end HW mode

As for PDO, do the following:
1. write code to verify enclave attestation verification report in CCF based PDO-TP
2.  write the equivalent of register-with-ledger.sh (for CCF ledger) that is used as part of the PDO build process. The script currently is hard-coded to work with the Sawtooth ledger.

As for CCF, 
1. add support to sign the enclave application during the build process. 
2. Specify the open enclave configuration.

**Comment by bvavala** [comment] 2022-10-13 17:11
This commit https://github.com/hyperledger-labs/private-data-objects/commit/ef4a4b2f794584b3ab6efc5c7f45ec9416d720b6 contains some of the changes that are necessary to run PDO in HW mode with CCF -- particularly the docker build/tests.

Notes:
1. CCF does not accept a non-empty proof-data field (hence only works in SIM mode)
2. the pservice compiled in HW mode expects a valid proof-data field, when retrieving the enclave data from the ledger

**Comment by bvavala** [comment] 2022-10-14 08:41
This commit https://github.com/hyperledger-labs/private-data-objects/commit/dedbd50aff496d54e6ca785a9496486ad83fed52 is a test that I made to run everything in HW mode, without modifying fields or the compilation process -- it only skips the signature verification in CCF during register enclave (assuming that that was the only issue).

Good things:
- the build succeeds
- even some initial tests in docker compose succeed

Bad things:
1. there's a bug in the ccf submitter
2. the pservice fails to verify the enclave. The failure happens when checking the expected report data in `VerifyEnclaveInfo`. Interestingly enough, that's "just" the last check. I think that the issue is probably due to some unexpected formatting coming from CCF, since the TP packs the blob to be delivered.

_Temporarily_, to make sure that at least the eservice runs fine in HW mode with CCF, this commit https://github.com/bvavala/private-data-objects/commit/9b9ad361a52be415d503cabfaf8d870baf14c761 does the following:
- it does not modify the CCF PDO TP
- when HW mode is selected, the eservice is compiled in hw-mode, while the pservice is compiled in sim-mode (to avoid verification of the proof data)
- it forces the eservice's proof data to be empty (in pdo_helper, so the TP still executes correctly)
- it successfully runs the CI (both SIM and HW mode)
These small temporary modifications are about 20 lines in 3 files, easy to revert as we fix the HW mode.

**Comment by bvavala** [comment] 2023-03-27 22:33
The "as for PDO" part in the description has been addressed in #406 .

**Comment by cmickeyb** [comment] 2023-04-04 17:28
Closing this. CCF nodes running in HW mode is #426

**Closed** 2023-04-04 17:28 UTC
Labels: enhancement
